// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQNcoheJLs40YlGUeVPuIo_CF84zqHEw',
    appId: '1:680295500804:web:eb887d05ebddaaa4bfb951',
    messagingSenderId: '680295500804',
    projectId: 'iqalqalah',
    authDomain: 'iqalqalah.firebaseapp.com',
    storageBucket: 'iqalqalah.firebasestorage.app',
    measurementId: 'G-B8K6SQ8J23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVAfIV9v3niGo8bqcDqQbNc8MxXZgmId8',
    appId: '1:680295500804:android:9e30f01c47380b9bbfb951',
    messagingSenderId: '680295500804',
    projectId: 'iqalqalah',
    storageBucket: 'iqalqalah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPeH_BDGdaEmRWZ6cJ58B4Vy5Sqoq8dM',
    appId: '1:680295500804:ios:c4e833142ce0ad6dbfb951',
    messagingSenderId: '680295500804',
    projectId: 'iqalqalah',
    storageBucket: 'iqalqalah.firebasestorage.app',
    iosBundleId: 'com.example.iqalqalah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPeH_BDGdaEmRWZ6cJ58B4Vy5Sqoq8dM',
    appId: '1:680295500804:ios:c4e833142ce0ad6dbfb951',
    messagingSenderId: '680295500804',
    projectId: 'iqalqalah',
    storageBucket: 'iqalqalah.firebasestorage.app',
    iosBundleId: 'com.example.iqalqalah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQNcoheJLs40YlGUeVPuIo_CF84zqHEw',
    appId: '1:680295500804:web:71f2ddf79800c4d1bfb951',
    messagingSenderId: '680295500804',
    projectId: 'iqalqalah',
    authDomain: 'iqalqalah.firebaseapp.com',
    storageBucket: 'iqalqalah.firebasestorage.app',
    measurementId: 'G-PE8HNKC8H6',
  );
}
